## Site Meta ##
# The title of the website.
title: "Photo Gallery"
# The description of the website
description: "Photo Archive"
# Keywords/tags for you site.
keywords: "lens, jeykll-lens, jekyll, theme, jekyll-theme, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: ""

## Site Configurations ##
# 1st heading of the site.
header: ""
# 2nd heading/sub heading of the website.
subheader: ""
# A description/bio of the website.
bio: ""
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: ""
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
